# Set Schiit USB Multibit to maximum quality (32-bit/192kHz)

monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.usb-Schiit_Audio_Schiit_USB_Multibit-00.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        audio.format = "S32LE"
        audio.rate = 192000
        api.alsa.period-size = 1024
        api.alsa.headroom = 8192
      }
    }
  }
]