# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Polkit
exec-once = /usr/libexec/polkit-mate-authentication-agent-1

# XDG Desktop Portal for proper URL handling
exec-once = /usr/libexec/xdg-desktop-portal-hyprland
exec-once = /usr/libexec/xdg-desktop-portal
