#!/bin/bash
# The content of this script will be generated by switchwall.sh - Don't modify it by yourself.
# Restore static wallpaper with swww if available
if command -v swww &>/dev/null; then
    current_wallpaper=$(jq -r '.background.wallpaperPath' "/home/elliot/.config/illogical-impulse/config.json" 2>/dev/null)
    if [[ -f "$current_wallpaper" ]]; then
        # Ensure swww daemon is running
        if ! pgrep -f "swww-daemon" > /dev/null; then
            swww-daemon &
            sleep 1
        fi
        swww img "$current_wallpaper" --transition-type fade
    fi
fi
